-- Reconstructed from the live catalog by READ ONLY inspection, 2026-09-10 (#633).
-- For an EMPTY, explicitly authorized database only. Not an upgrade or a data backup.
-- CREATE SCHEMA intentionally fails if gradebook exists. No DROP, reset, credentials,
-- database-wide settings, legacy streams/versions or real academic data are included.
BEGIN;
CREATE SCHEMA gradebook;

CREATE TABLE gradebook.aluno (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint NOT NULL,
  nome text NOT NULL,
  conselho_anterior boolean,
  conselho_anterior_por uuid,
  conselho_anterior_em timestamp with time zone
);
CREATE TABLE gradebook.ano_letivo (
  ano smallint NOT NULL,
  minimo_aprovacao integer NOT NULL,
  max_componentes_conselho smallint NOT NULL
);
CREATE TABLE gradebook.ano_letivo_historico (
  ano smallint NOT NULL,
  minimo_aprovacao_anterior integer NOT NULL,
  minimo_aprovacao_novo integer NOT NULL,
  max_componentes_conselho_anterior smallint NOT NULL,
  max_componentes_conselho_novo smallint NOT NULL,
  alterado_por uuid NOT NULL,
  alterado_em timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE gradebook.conselho_anterior_historico (
  aluno_id integer NOT NULL,
  valor_anterior boolean,
  valor_novo boolean,
  alterado_por uuid NOT NULL,
  alterado_em timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE gradebook.conselho_decisao (
  aluno_id integer NOT NULL,
  decisao smallint NOT NULL,
  justificativa text NOT NULL,
  registrado_por uuid NOT NULL,
  registrado_em timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE gradebook.conselho_decisao_historico (
  aluno_id integer NOT NULL,
  decisao_anterior smallint NOT NULL,
  decisao_nova smallint NOT NULL,
  justificativa_anterior text NOT NULL,
  justificativa_nova text NOT NULL,
  alterado_por uuid NOT NULL,
  alterado_em timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE gradebook.disciplina (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint NOT NULL,
  nome text NOT NULL
);
CREATE TABLE gradebook.fechamento (
  oferta_id integer NOT NULL,
  aluno_id integer NOT NULL,
  am1_fonte integer,
  am2_fonte integer,
  am3_fonte integer,
  rec1 integer,
  rec2 integer,
  rec3 integer,
  rec_nc_mask smallint DEFAULT 0 NOT NULL,
  u_fonte integer
);
CREATE TABLE gradebook.fechamento_historico (
  importacao_id integer NOT NULL,
  oferta_id integer NOT NULL,
  aluno_id integer NOT NULL,
  campo smallint NOT NULL,
  valor_anterior integer,
  valor_novo integer,
  estado_anterior smallint NOT NULL,
  estado_novo smallint NOT NULL
);
CREATE TABLE gradebook.importacao (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint NOT NULL,
  tipo smallint NOT NULL,
  arquivo text NOT NULL,
  hash bytea NOT NULL,
  criado_em timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE gradebook.importacao_diagnostico (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint,
  arquivo text NOT NULL,
  hash bytea NOT NULL,
  chave text NOT NULL,
  nivel text NOT NULL,
  codigo text NOT NULL,
  turma_codigo text,
  disciplina text,
  periodo text,
  aluno_numero smallint,
  campo text,
  rotulo text,
  valor_encontrado text,
  causa text,
  guia text,
  celula text,
  primeiro_em timestamp with time zone DEFAULT now() NOT NULL,
  ultimo_em timestamp with time zone DEFAULT now() NOT NULL,
  ocorrencias integer DEFAULT 1 NOT NULL
);
CREATE TABLE gradebook.instrumento (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  oferta_id integer NOT NULL,
  trimestre smallint NOT NULL,
  slot smallint NOT NULL,
  maximo integer,
  descricao text
);
CREATE TABLE gradebook.instrumento_historico (
  importacao_id integer NOT NULL,
  instrumento_id integer NOT NULL,
  maximo_anterior integer,
  maximo_novo integer,
  descricao_anterior text,
  descricao_nova text
);
CREATE TABLE gradebook.nota (
  instrumento_id integer NOT NULL,
  aluno_id integer NOT NULL,
  valor integer NOT NULL
);
CREATE TABLE gradebook.nota_historico (
  importacao_id integer NOT NULL,
  instrumento_id integer NOT NULL,
  aluno_id integer NOT NULL,
  valor_anterior integer,
  valor_novo integer
);
CREATE TABLE gradebook.oferta (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint NOT NULL,
  turma_id integer NOT NULL,
  professor_id integer NOT NULL,
  disciplina_id integer NOT NULL
);
CREATE TABLE gradebook.professor (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint NOT NULL,
  nome text NOT NULL
);
CREATE TABLE gradebook.turma (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ano smallint NOT NULL,
  codigo text NOT NULL,
  nome text NOT NULL,
  etapa smallint NOT NULL,
  turno text NOT NULL
);
CREATE TABLE gradebook.vinculo (
  ano smallint NOT NULL,
  turma_id integer NOT NULL,
  numero smallint NOT NULL,
  aluno_id integer NOT NULL,
  situacao smallint,
  turma_relacionada_id integer
);
CREATE TABLE gradebook.vinculo_historico (
  importacao_id integer NOT NULL,
  turma_id integer NOT NULL,
  numero smallint NOT NULL,
  situacao_anterior smallint,
  situacao_nova smallint,
  turma_rel_anterior integer,
  turma_rel_nova integer
);

-- Keys first, then checks and references: no dependency on table creation order.
ALTER TABLE gradebook.aluno ADD CONSTRAINT aluno_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.ano_letivo ADD CONSTRAINT ano_letivo_pkey PRIMARY KEY (ano);
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_pk PRIMARY KEY (ano, alterado_em);
ALTER TABLE gradebook.conselho_anterior_historico ADD CONSTRAINT conselho_anterior_historico_pk PRIMARY KEY (aluno_id, alterado_em);
ALTER TABLE gradebook.conselho_decisao ADD CONSTRAINT conselho_decisao_pkey PRIMARY KEY (aluno_id);
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_pk PRIMARY KEY (aluno_id, alterado_em);
ALTER TABLE gradebook.disciplina ADD CONSTRAINT disciplina_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_pk PRIMARY KEY (oferta_id, aluno_id);
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_pk PRIMARY KEY (importacao_id, oferta_id, aluno_id, campo);
ALTER TABLE gradebook.importacao ADD CONSTRAINT importacao_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.instrumento ADD CONSTRAINT instrumento_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.instrumento_historico ADD CONSTRAINT instrumento_historico_pk PRIMARY KEY (importacao_id, instrumento_id);
ALTER TABLE gradebook.nota ADD CONSTRAINT nota_pk PRIMARY KEY (instrumento_id, aluno_id);
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_pk PRIMARY KEY (importacao_id, instrumento_id, aluno_id);
ALTER TABLE gradebook.oferta ADD CONSTRAINT oferta_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.professor ADD CONSTRAINT professor_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.turma ADD CONSTRAINT turma_pkey PRIMARY KEY (id);
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_pk PRIMARY KEY (turma_id, numero);
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_pk PRIMARY KEY (importacao_id, turma_id, numero);
ALTER TABLE gradebook.aluno ADD CONSTRAINT aluno_id_ano_uk UNIQUE (id, ano);
ALTER TABLE gradebook.disciplina ADD CONSTRAINT disciplina_id_ano_uk UNIQUE (id, ano);
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_hash_chave_uk UNIQUE (hash, chave);
ALTER TABLE gradebook.instrumento ADD CONSTRAINT instrumento_logico_uk UNIQUE (oferta_id, trimestre, slot);
ALTER TABLE gradebook.oferta ADD CONSTRAINT oferta_logica_uk UNIQUE (ano, turma_id, disciplina_id, professor_id);
ALTER TABLE gradebook.professor ADD CONSTRAINT professor_id_ano_uk UNIQUE (id, ano);
ALTER TABLE gradebook.turma ADD CONSTRAINT turma_id_ano_uk UNIQUE (id, ano);

ALTER TABLE gradebook.aluno ADD CONSTRAINT aluno_conselho_anterior_auditoria_ck CHECK ((((conselho_anterior IS NULL) AND (conselho_anterior_por IS NULL) AND (conselho_anterior_em IS NULL)) OR ((conselho_anterior IS NOT NULL) AND (conselho_anterior_por IS NOT NULL) AND (conselho_anterior_em IS NOT NULL))));
ALTER TABLE gradebook.ano_letivo ADD CONSTRAINT ano_letivo_max_componentes_conselho_ck CHECK ((max_componentes_conselho >= 0));
ALTER TABLE gradebook.ano_letivo ADD CONSTRAINT ano_letivo_minimo_aprovacao_ck CHECK ((minimo_aprovacao >= 0));
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_delta_real_ck CHECK (((minimo_aprovacao_anterior IS DISTINCT FROM minimo_aprovacao_novo) OR (max_componentes_conselho_anterior IS DISTINCT FROM max_componentes_conselho_novo)));
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_max_ant_ck CHECK ((max_componentes_conselho_anterior >= 0));
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_max_novo_ck CHECK ((max_componentes_conselho_novo >= 0));
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_min_ant_ck CHECK ((minimo_aprovacao_anterior >= 0));
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_min_novo_ck CHECK ((minimo_aprovacao_novo >= 0));
ALTER TABLE gradebook.conselho_anterior_historico ADD CONSTRAINT conselho_anterior_historico_delta_real_ck CHECK ((valor_anterior IS DISTINCT FROM valor_novo));
ALTER TABLE gradebook.conselho_decisao ADD CONSTRAINT conselho_decisao_codigo_ck CHECK ((decisao = ANY (ARRAY[1, 2, 3])));
ALTER TABLE gradebook.conselho_decisao ADD CONSTRAINT conselho_decisao_justificativa_ck CHECK ((btrim(justificativa) <> ''::text));
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_codigo_anterior_ck CHECK ((decisao_anterior = ANY (ARRAY[1, 2, 3])));
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_codigo_novo_ck CHECK ((decisao_nova = ANY (ARRAY[1, 2, 3])));
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_delta_real_ck CHECK (((decisao_anterior IS DISTINCT FROM decisao_nova) OR (justificativa_anterior IS DISTINCT FROM justificativa_nova)));
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_just_ant_ck CHECK ((btrim(justificativa_anterior) <> ''::text));
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_just_nova_ck CHECK ((btrim(justificativa_nova) <> ''::text));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_am1_ck CHECK (((am1_fonte IS NULL) OR (am1_fonte >= 0)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_am2_ck CHECK (((am2_fonte IS NULL) OR (am2_fonte >= 0)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_am3_ck CHECK (((am3_fonte IS NULL) OR (am3_fonte >= 0)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec1_ck CHECK (((rec1 IS NULL) OR (rec1 >= 0)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec1_nc_ck CHECK (((((rec_nc_mask)::integer & 1) = 0) OR (rec1 IS NULL)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec2_ck CHECK (((rec2 IS NULL) OR (rec2 >= 0)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec2_nc_ck CHECK (((((rec_nc_mask)::integer & 2) = 0) OR (rec2 IS NULL)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec3_ck CHECK (((rec3 IS NULL) OR (rec3 >= 0)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec3_nc_ck CHECK (((((rec_nc_mask)::integer & 4) = 0) OR (rec3 IS NULL)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_rec_nc_mask_ck CHECK (((rec_nc_mask >= 0) AND (rec_nc_mask <= 7)));
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_u_ck CHECK (((u_fonte IS NULL) OR (u_fonte >= 0)));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_campo_ck CHECK (((campo >= 1) AND (campo <= 7)));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_delta_real_ck CHECK (((estado_anterior IS DISTINCT FROM estado_novo) OR (valor_anterior IS DISTINCT FROM valor_novo)));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_estado_anterior_ck CHECK (((estado_anterior >= 0) AND (estado_anterior <= 2)));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_estado_novo_ck CHECK (((estado_novo >= 0) AND (estado_novo <= 2)));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_nc_so_rec_anterior_ck CHECK (((estado_anterior <> 2) OR (campo = ANY (ARRAY[4, 5, 6]))));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_nc_so_rec_novo_ck CHECK (((estado_novo <> 2) OR (campo = ANY (ARRAY[4, 5, 6]))));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_valor_estado_anterior_ck CHECK ((((estado_anterior = 1) AND (valor_anterior IS NOT NULL) AND (valor_anterior >= 0)) OR ((estado_anterior = ANY (ARRAY[0, 2])) AND (valor_anterior IS NULL))));
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_valor_estado_novo_ck CHECK ((((estado_novo = 1) AND (valor_novo IS NOT NULL) AND (valor_novo >= 0)) OR ((estado_novo = ANY (ARRAY[0, 2])) AND (valor_novo IS NULL))));
ALTER TABLE gradebook.importacao ADD CONSTRAINT importacao_hash_sha256_ck CHECK ((octet_length(hash) = 32));
ALTER TABLE gradebook.importacao ADD CONSTRAINT importacao_tipo_ck CHECK ((tipo = ANY (ARRAY[1, 2])));
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_aluno_numero_ck CHECK (((aluno_numero IS NULL) OR (aluno_numero > 0)));
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_ano_ck CHECK (((ano IS NULL) OR ((ano >= 2000) AND (ano <= 9999))));
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_hash_ck CHECK ((octet_length(hash) = 32));
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_nivel_ck CHECK ((nivel = ANY (ARRAY['warning'::text, 'blocking-error'::text])));
ALTER TABLE gradebook.importacao_diagnostico ADD CONSTRAINT importacao_diagnostico_ocorrencias_ck CHECK ((ocorrencias > 0));
ALTER TABLE gradebook.instrumento ADD CONSTRAINT instrumento_maximo_ck CHECK (((maximo IS NULL) OR (maximo > 0)));
ALTER TABLE gradebook.instrumento ADD CONSTRAINT instrumento_slot_ck CHECK (((slot = ANY (ARRAY[1, 2, 3])) OR ((slot >= 11) AND (slot <= 20))));
ALTER TABLE gradebook.instrumento ADD CONSTRAINT instrumento_trimestre_ck CHECK (((trimestre >= 1) AND (trimestre <= 3)));
ALTER TABLE gradebook.instrumento_historico ADD CONSTRAINT instrumento_historico_delta_real_ck CHECK (((maximo_anterior IS DISTINCT FROM maximo_novo) OR (descricao_anterior IS DISTINCT FROM descricao_nova)));
ALTER TABLE gradebook.instrumento_historico ADD CONSTRAINT instrumento_historico_maximo_anterior_ck CHECK (((maximo_anterior IS NULL) OR (maximo_anterior > 0)));
ALTER TABLE gradebook.instrumento_historico ADD CONSTRAINT instrumento_historico_maximo_novo_ck CHECK (((maximo_novo IS NULL) OR (maximo_novo > 0)));
ALTER TABLE gradebook.nota ADD CONSTRAINT nota_valor_ck CHECK ((valor >= 0));
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_delta_real_ck CHECK ((valor_anterior IS DISTINCT FROM valor_novo));
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_valor_anterior_ck CHECK (((valor_anterior IS NULL) OR (valor_anterior >= 0)));
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_valor_novo_ck CHECK (((valor_novo IS NULL) OR (valor_novo >= 0)));
ALTER TABLE gradebook.turma ADD CONSTRAINT turma_etapa_ck CHECK ((etapa > 0));
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_numero_ck CHECK ((numero > 0));
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_situacao_ck CHECK (((situacao IS NULL) OR ((situacao >= 1) AND (situacao <= 7))));
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_situacao_turma_relacionada_ck CHECK ((((situacao = ANY (ARRAY[6, 7])) AND (turma_relacionada_id IS NOT NULL)) OR (((situacao IS NULL) OR (situacao <> ALL (ARRAY[6, 7]))) AND (turma_relacionada_id IS NULL))));
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_delta_real_ck CHECK (((situacao_anterior IS DISTINCT FROM situacao_nova) OR (turma_rel_anterior IS DISTINCT FROM turma_rel_nova)));
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_numero_ck CHECK ((numero > 0));
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_rel_anterior_ck CHECK ((((situacao_anterior = ANY (ARRAY[6, 7])) AND (turma_rel_anterior IS NOT NULL)) OR (((situacao_anterior IS NULL) OR (situacao_anterior <> ALL (ARRAY[6, 7]))) AND (turma_rel_anterior IS NULL))));
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_rel_nova_ck CHECK ((((situacao_nova = ANY (ARRAY[6, 7])) AND (turma_rel_nova IS NOT NULL)) OR (((situacao_nova IS NULL) OR (situacao_nova <> ALL (ARRAY[6, 7]))) AND (turma_rel_nova IS NULL))));
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_situacao_anterior_ck CHECK (((situacao_anterior IS NULL) OR ((situacao_anterior >= 1) AND (situacao_anterior <= 7))));
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_situacao_nova_ck CHECK (((situacao_nova IS NULL) OR ((situacao_nova >= 1) AND (situacao_nova <= 7))));

ALTER TABLE gradebook.aluno ADD CONSTRAINT aluno_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.ano_letivo_historico ADD CONSTRAINT ano_letivo_historico_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.conselho_anterior_historico ADD CONSTRAINT conselho_anterior_historico_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.conselho_decisao ADD CONSTRAINT conselho_decisao_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.conselho_decisao_historico ADD CONSTRAINT conselho_decisao_historico_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.disciplina ADD CONSTRAINT disciplina_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.fechamento ADD CONSTRAINT fechamento_oferta_fk FOREIGN KEY (oferta_id) REFERENCES gradebook.oferta(id);
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_importacao_fk FOREIGN KEY (importacao_id) REFERENCES gradebook.importacao(id);
ALTER TABLE gradebook.fechamento_historico ADD CONSTRAINT fechamento_historico_oferta_fk FOREIGN KEY (oferta_id) REFERENCES gradebook.oferta(id);
ALTER TABLE gradebook.importacao ADD CONSTRAINT importacao_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE gradebook.instrumento ADD CONSTRAINT instrumento_oferta_fk FOREIGN KEY (oferta_id) REFERENCES gradebook.oferta(id);
ALTER TABLE gradebook.instrumento_historico ADD CONSTRAINT instrumento_historico_importacao_fk FOREIGN KEY (importacao_id) REFERENCES gradebook.importacao(id);
ALTER TABLE gradebook.instrumento_historico ADD CONSTRAINT instrumento_historico_instrumento_fk FOREIGN KEY (instrumento_id) REFERENCES gradebook.instrumento(id);
ALTER TABLE gradebook.nota ADD CONSTRAINT nota_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.nota ADD CONSTRAINT nota_instrumento_fk FOREIGN KEY (instrumento_id) REFERENCES gradebook.instrumento(id);
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_aluno_fk FOREIGN KEY (aluno_id) REFERENCES gradebook.aluno(id);
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_importacao_fk FOREIGN KEY (importacao_id) REFERENCES gradebook.importacao(id);
ALTER TABLE gradebook.nota_historico ADD CONSTRAINT nota_historico_instrumento_fk FOREIGN KEY (instrumento_id) REFERENCES gradebook.instrumento(id);
ALTER TABLE gradebook.oferta ADD CONSTRAINT oferta_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.oferta ADD CONSTRAINT oferta_disciplina_ano_fk FOREIGN KEY (disciplina_id, ano) REFERENCES gradebook.disciplina(id, ano);
ALTER TABLE gradebook.oferta ADD CONSTRAINT oferta_professor_ano_fk FOREIGN KEY (professor_id, ano) REFERENCES gradebook.professor(id, ano);
ALTER TABLE gradebook.oferta ADD CONSTRAINT oferta_turma_ano_fk FOREIGN KEY (turma_id, ano) REFERENCES gradebook.turma(id, ano);
ALTER TABLE gradebook.professor ADD CONSTRAINT professor_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.turma ADD CONSTRAINT turma_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_aluno_ano_fk FOREIGN KEY (aluno_id, ano) REFERENCES gradebook.aluno(id, ano);
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_ano_fk FOREIGN KEY (ano) REFERENCES gradebook.ano_letivo(ano);
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_turma_ano_fk FOREIGN KEY (turma_id, ano) REFERENCES gradebook.turma(id, ano);
ALTER TABLE gradebook.vinculo ADD CONSTRAINT vinculo_turma_relacionada_ano_fk FOREIGN KEY (turma_relacionada_id, ano) REFERENCES gradebook.turma(id, ano);
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_importacao_fk FOREIGN KEY (importacao_id) REFERENCES gradebook.importacao(id);
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_turma_fk FOREIGN KEY (turma_id) REFERENCES gradebook.turma(id);
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_turma_rel_anterior_fk FOREIGN KEY (turma_rel_anterior) REFERENCES gradebook.turma(id);
ALTER TABLE gradebook.vinculo_historico ADD CONSTRAINT vinculo_historico_turma_rel_nova_fk FOREIGN KEY (turma_rel_nova) REFERENCES gradebook.turma(id);

CREATE INDEX aluno_ano_nome_idx ON gradebook.aluno USING btree (ano, nome);
CREATE UNIQUE INDEX disciplina_ano_nome_norm_uidx ON gradebook.disciplina USING btree (ano, lower(btrim(nome)));
CREATE INDEX fechamento_aluno_idx ON gradebook.fechamento USING btree (aluno_id);
CREATE INDEX importacao_ano_criado_em_idx ON gradebook.importacao USING btree (ano, criado_em);
CREATE INDEX importacao_diagnostico_ano_ultimo_idx ON gradebook.importacao_diagnostico USING btree (ano, ultimo_em DESC);
CREATE INDEX importacao_diagnostico_nivel_codigo_idx ON gradebook.importacao_diagnostico USING btree (nivel, codigo, ultimo_em DESC);
CREATE INDEX nota_aluno_idx ON gradebook.nota USING btree (aluno_id);
CREATE UNIQUE INDEX professor_ano_nome_norm_uidx ON gradebook.professor USING btree (ano, lower(btrim(nome)));
CREATE UNIQUE INDEX turma_ano_codigo_norm_uidx ON gradebook.turma USING btree (ano, upper(btrim(codigo)));
CREATE INDEX vinculo_aluno_idx ON gradebook.vinculo USING btree (aluno_id);
CREATE UNIQUE INDEX vinculo_um_corrente_por_aluno_uidx ON gradebook.vinculo USING btree (aluno_id) WHERE (situacao IS DISTINCT FROM 6);

CREATE OR REPLACE FUNCTION gradebook.aluno_possui_vinculo_na_oferta(p_aluno_id integer, p_oferta_id integer)
 RETURNS boolean LANGUAGE sql STABLE SET search_path TO 'pg_catalog', 'gradebook'
AS $function$
    SELECT EXISTS (
      SELECT 1 FROM gradebook.oferta o
      JOIN gradebook.vinculo v ON v.turma_id = o.turma_id AND v.aluno_id = p_aluno_id
      WHERE o.id = p_oferta_id
    );
$function$;

CREATE OR REPLACE FUNCTION gradebook.preparar_conselho_anterior()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog', 'gradebook'
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.conselho_anterior IS NULL THEN
            NEW.conselho_anterior_por := NULL;
            NEW.conselho_anterior_em := NULL;
        ELSE
            IF NEW.conselho_anterior_por IS NULL THEN
                RAISE EXCEPTION 'conselho_anterior_por e obrigatorio quando conselho_anterior e informado';
            END IF;
            NEW.conselho_anterior_em := now();
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.conselho_anterior IS DISTINCT FROM OLD.conselho_anterior THEN
        IF NEW.conselho_anterior IS NULL THEN
            NEW.conselho_anterior_por := NULL;
            NEW.conselho_anterior_em := NULL;
        ELSE
            IF NEW.conselho_anterior_por IS NULL THEN
                RAISE EXCEPTION 'conselho_anterior_por e obrigatorio quando conselho_anterior e alterado';
            END IF;
            NEW.conselho_anterior_em := now();
        END IF;
    ELSE
        NEW.conselho_anterior_por := OLD.conselho_anterior_por;
        NEW.conselho_anterior_em := OLD.conselho_anterior_em;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION gradebook.validar_fechamento_vinculo()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog', 'gradebook'
AS $function$
BEGIN
    IF NOT gradebook.aluno_possui_vinculo_na_oferta(NEW.aluno_id, NEW.oferta_id) THEN
      RAISE EXCEPTION 'Aluno % nao possui vinculo com a turma da oferta %', NEW.aluno_id, NEW.oferta_id;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION gradebook.validar_nota_vinculo()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'pg_catalog', 'gradebook'
AS $function$
DECLARE v_oferta_id INTEGER;
BEGIN
    SELECT i.oferta_id INTO v_oferta_id FROM gradebook.instrumento i WHERE i.id = NEW.instrumento_id;
    IF v_oferta_id IS NULL THEN RAISE EXCEPTION 'Instrumento % inexistente para nota', NEW.instrumento_id; END IF;
    IF NOT gradebook.aluno_possui_vinculo_na_oferta(NEW.aluno_id, v_oferta_id) THEN
      RAISE EXCEPTION 'Aluno % nao possui vinculo com a turma da oferta %', NEW.aluno_id, v_oferta_id;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER aluno_preparar_conselho_anterior_trg BEFORE INSERT OR UPDATE OF conselho_anterior, conselho_anterior_por, conselho_anterior_em ON gradebook.aluno FOR EACH ROW EXECUTE FUNCTION gradebook.preparar_conselho_anterior();
CREATE TRIGGER fechamento_validar_vinculo_trg BEFORE INSERT OR UPDATE OF oferta_id, aluno_id ON gradebook.fechamento FOR EACH ROW EXECUTE FUNCTION gradebook.validar_fechamento_vinculo();
CREATE TRIGGER nota_validar_vinculo_trg BEFORE INSERT OR UPDATE OF instrumento_id, aluno_id ON gradebook.nota FOR EACH ROW EXECUTE FUNCTION gradebook.validar_nota_vinculo();

-- Backend-only boundary. Provision/grant the dedicated application role separately.
REVOKE ALL ON SCHEMA gradebook FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA gradebook FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA gradebook FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA gradebook FROM PUBLIC;
COMMIT;
