-- #625 — auditoria compacta de diagnósticos da importação simplificada.
-- Não altera fatos acadêmicos. Registra somente ocorrências de validação/qualidade da fonte.

CREATE TABLE gradebook.importacao_diagnostico (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano               SMALLINT NULL,
  arquivo           TEXT NOT NULL,
  hash              BYTEA NOT NULL,
  chave             TEXT NOT NULL,
  nivel             TEXT NOT NULL,
  codigo            TEXT NOT NULL,
  turma_codigo      TEXT NULL,
  disciplina        TEXT NULL,
  periodo           TEXT NULL,
  aluno_numero      SMALLINT NULL,
  campo             TEXT NULL,
  rotulo            TEXT NULL,
  valor_encontrado  TEXT NULL,
  causa             TEXT NULL,
  guia              TEXT NULL,
  celula            TEXT NULL,
  primeiro_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  ultimo_em         TIMESTAMPTZ NOT NULL DEFAULT now(),
  ocorrencias       INTEGER NOT NULL DEFAULT 1,

  CONSTRAINT importacao_diagnostico_hash_ck CHECK (octet_length(hash) = 32),
  CONSTRAINT importacao_diagnostico_nivel_ck CHECK (nivel IN ('warning', 'blocking-error')),
  CONSTRAINT importacao_diagnostico_ano_ck CHECK (ano IS NULL OR ano BETWEEN 2000 AND 9999),
  CONSTRAINT importacao_diagnostico_aluno_numero_ck CHECK (aluno_numero IS NULL OR aluno_numero > 0),
  CONSTRAINT importacao_diagnostico_ocorrencias_ck CHECK (ocorrencias > 0),
  CONSTRAINT importacao_diagnostico_hash_chave_uk UNIQUE (hash, chave)
);

CREATE INDEX importacao_diagnostico_ano_ultimo_idx
  ON gradebook.importacao_diagnostico (ano, ultimo_em DESC);

CREATE INDEX importacao_diagnostico_nivel_codigo_idx
  ON gradebook.importacao_diagnostico (nivel, codigo, ultimo_em DESC);

GRANT SELECT, INSERT, UPDATE ON gradebook.importacao_diagnostico TO gradebook_app;
GRANT USAGE, SELECT ON SEQUENCE gradebook.importacao_diagnostico_id_seq TO gradebook_app;
