-- #648 / #635 — Conselho relacional V3, aditivo e restrito ao fluxo corrente.
-- Não remove/converte colunas históricas, não faz backfill e não altera fatos acadêmicos.
BEGIN;

CREATE TABLE gradebook.conselho_sessao (
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  estado SMALLINT NOT NULL,
  versao BIGINT NOT NULL,
  fechamento_atual_id BIGINT NULL,
  atualizado_por UUID NOT NULL,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT conselho_sessao_pk PRIMARY KEY (ano, turma_id),
  CONSTRAINT conselho_sessao_estado_ck CHECK (estado IN (1, 2)),
  CONSTRAINT conselho_sessao_versao_ck CHECK (versao > 0),
  CONSTRAINT conselho_sessao_turma_fk FOREIGN KEY (turma_id, ano)
    REFERENCES gradebook.turma(id, ano)
);

CREATE TABLE gradebook.conselho_sessao_historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  versao BIGINT NOT NULL,
  evento SMALLINT NOT NULL,
  estado_anterior SMALLINT NULL,
  estado_novo SMALLINT NOT NULL,
  justificativa TEXT NOT NULL,
  alterado_por UUID NOT NULL,
  alterado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  chave_idempotencia TEXT NOT NULL,
  CONSTRAINT conselho_sessao_hist_evento_ck CHECK (evento IN (1, 2, 3)),
  CONSTRAINT conselho_sessao_hist_estado_ant_ck CHECK (estado_anterior IS NULL OR estado_anterior IN (1, 2)),
  CONSTRAINT conselho_sessao_hist_estado_novo_ck CHECK (estado_novo IN (1, 2)),
  CONSTRAINT conselho_sessao_hist_versao_ck CHECK (versao > 0),
  CONSTRAINT conselho_sessao_hist_justificativa_ck CHECK (btrim(justificativa) <> ''),
  CONSTRAINT conselho_sessao_hist_chave_ck CHECK (btrim(chave_idempotencia) <> ''),
  CONSTRAINT conselho_sessao_hist_versao_uk UNIQUE (ano, turma_id, versao),
  CONSTRAINT conselho_sessao_hist_chave_uk UNIQUE (chave_idempotencia),
  CONSTRAINT conselho_sessao_hist_sessao_fk FOREIGN KEY (ano, turma_id)
    REFERENCES gradebook.conselho_sessao(ano, turma_id)
);

CREATE TABLE gradebook.conselho_idempotencia (
  chave TEXT PRIMARY KEY,
  operacao SMALLINT NOT NULL,
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  aluno_id INTEGER NULL,
  versao_anterior BIGINT NOT NULL,
  versao_nova BIGINT NOT NULL,
  decisao SMALLINT NULL,
  favoraveis INTEGER NULL,
  contrarios INTEGER NULL,
  justificativa TEXT NOT NULL,
  registrado_por UUID NOT NULL,
  registrado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT conselho_idempotencia_operacao_ck CHECK (operacao IN (1, 2, 3, 4, 5)),
  CONSTRAINT conselho_idempotencia_chave_ck CHECK (btrim(chave) <> ''),
  CONSTRAINT conselho_idempotencia_versao_ck CHECK (versao_anterior >= 0 AND versao_nova > versao_anterior),
  CONSTRAINT conselho_idempotencia_justificativa_ck CHECK (btrim(justificativa) <> ''),
  CONSTRAINT conselho_idempotencia_aluno_ck CHECK ((operacao IN (2, 3)) = (aluno_id IS NOT NULL)),
  CONSTRAINT conselho_idempotencia_decisao_ck CHECK (
    (operacao = 2 AND decisao IN (1, 2, 3)) OR (operacao <> 2 AND decisao IS NULL)
  ),
  CONSTRAINT conselho_idempotencia_votos_ck CHECK (
    (operacao = 3 AND favoraveis >= 0 AND contrarios >= 0) OR
    (operacao <> 3 AND favoraveis IS NULL AND contrarios IS NULL)
  ),
  CONSTRAINT conselho_idempotencia_turma_fk FOREIGN KEY (turma_id, ano)
    REFERENCES gradebook.turma(id, ano),
  CONSTRAINT conselho_idempotencia_aluno_fk FOREIGN KEY (aluno_id, ano)
    REFERENCES gradebook.aluno(id, ano)
);

CREATE TABLE gradebook.conselho_votacao (
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  aluno_id INTEGER NOT NULL,
  favoraveis INTEGER NOT NULL,
  contrarios INTEGER NOT NULL,
  versao BIGINT NOT NULL,
  justificativa TEXT NOT NULL,
  registrado_por UUID NOT NULL,
  registrado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT conselho_votacao_pk PRIMARY KEY (ano, turma_id, aluno_id),
  CONSTRAINT conselho_votacao_favoraveis_ck CHECK (favoraveis >= 0),
  CONSTRAINT conselho_votacao_contrarios_ck CHECK (contrarios >= 0),
  CONSTRAINT conselho_votacao_versao_ck CHECK (versao > 0),
  CONSTRAINT conselho_votacao_justificativa_ck CHECK (btrim(justificativa) <> ''),
  CONSTRAINT conselho_votacao_sessao_fk FOREIGN KEY (ano, turma_id)
    REFERENCES gradebook.conselho_sessao(ano, turma_id),
  CONSTRAINT conselho_votacao_aluno_fk FOREIGN KEY (aluno_id, ano)
    REFERENCES gradebook.aluno(id, ano)
);

CREATE TABLE gradebook.conselho_votacao_historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  aluno_id INTEGER NOT NULL,
  versao BIGINT NOT NULL,
  favoraveis_anterior INTEGER NULL,
  contrarios_anterior INTEGER NULL,
  favoraveis_novo INTEGER NOT NULL,
  contrarios_novo INTEGER NOT NULL,
  justificativa TEXT NOT NULL,
  alterado_por UUID NOT NULL,
  alterado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  chave_idempotencia TEXT NOT NULL,
  CONSTRAINT conselho_votacao_hist_ant_ck CHECK (
    (favoraveis_anterior IS NULL AND contrarios_anterior IS NULL) OR
    (favoraveis_anterior >= 0 AND contrarios_anterior >= 0)
  ),
  CONSTRAINT conselho_votacao_hist_novo_ck CHECK (favoraveis_novo >= 0 AND contrarios_novo >= 0),
  CONSTRAINT conselho_votacao_hist_versao_ck CHECK (versao > 0),
  CONSTRAINT conselho_votacao_hist_justificativa_ck CHECK (btrim(justificativa) <> ''),
  CONSTRAINT conselho_votacao_hist_chave_uk UNIQUE (chave_idempotencia),
  CONSTRAINT conselho_votacao_hist_versao_uk UNIQUE (ano, turma_id, versao),
  CONSTRAINT conselho_votacao_hist_sessao_fk FOREIGN KEY (ano, turma_id)
    REFERENCES gradebook.conselho_sessao(ano, turma_id),
  CONSTRAINT conselho_votacao_hist_aluno_fk FOREIGN KEY (aluno_id, ano)
    REFERENCES gradebook.aluno(id, ano)
);

CREATE TABLE gradebook.conselho_decisao_comando (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  aluno_id INTEGER NOT NULL,
  versao BIGINT NOT NULL,
  decisao_anterior SMALLINT NULL,
  justificativa_anterior TEXT NULL,
  decisao_nova SMALLINT NOT NULL,
  justificativa_nova TEXT NOT NULL,
  alterado_por UUID NOT NULL,
  alterado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  chave_idempotencia TEXT NOT NULL,
  CONSTRAINT conselho_decisao_cmd_codigo_ant_ck CHECK (decisao_anterior IS NULL OR decisao_anterior IN (1, 2, 3)),
  CONSTRAINT conselho_decisao_cmd_ant_par_ck CHECK ((decisao_anterior IS NULL) = (justificativa_anterior IS NULL)),
  CONSTRAINT conselho_decisao_cmd_codigo_novo_ck CHECK (decisao_nova IN (1, 2, 3)),
  CONSTRAINT conselho_decisao_cmd_justificativa_ck CHECK (btrim(justificativa_nova) <> ''),
  CONSTRAINT conselho_decisao_cmd_versao_ck CHECK (versao > 0),
  CONSTRAINT conselho_decisao_cmd_chave_uk UNIQUE (chave_idempotencia),
  CONSTRAINT conselho_decisao_cmd_versao_uk UNIQUE (ano, turma_id, versao),
  CONSTRAINT conselho_decisao_cmd_sessao_fk FOREIGN KEY (ano, turma_id)
    REFERENCES gradebook.conselho_sessao(ano, turma_id),
  CONSTRAINT conselho_decisao_cmd_aluno_fk FOREIGN KEY (aluno_id, ano)
    REFERENCES gradebook.aluno(id, ano)
);

CREATE TABLE gradebook.conselho_fechamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano SMALLINT NOT NULL,
  turma_id INTEGER NOT NULL,
  sequencia SMALLINT NOT NULL,
  versao BIGINT NOT NULL,
  total INTEGER NOT NULL,
  elegiveis INTEGER NOT NULL,
  aprovados INTEGER NOT NULL,
  reprovados INTEGER NOT NULL,
  faltas INTEGER NOT NULL,
  nao_elegiveis INTEGER NOT NULL,
  justificativa TEXT NOT NULL,
  fechado_por UUID NOT NULL,
  fechado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  chave_idempotencia TEXT NOT NULL,
  CONSTRAINT conselho_fechamento_contagens_ck CHECK (
    total >= 0 AND elegiveis >= 0 AND aprovados >= 0 AND reprovados >= 0 AND
    faltas >= 0 AND nao_elegiveis >= 0 AND elegiveis + nao_elegiveis = total AND
    aprovados + reprovados + faltas = elegiveis
  ),
  CONSTRAINT conselho_fechamento_sequencia_ck CHECK (sequencia > 0),
  CONSTRAINT conselho_fechamento_versao_ck CHECK (versao > 0),
  CONSTRAINT conselho_fechamento_justificativa_ck CHECK (btrim(justificativa) <> ''),
  CONSTRAINT conselho_fechamento_turma_seq_uk UNIQUE (ano, turma_id, sequencia),
  CONSTRAINT conselho_fechamento_chave_uk UNIQUE (chave_idempotencia),
  CONSTRAINT conselho_fechamento_sessao_fk FOREIGN KEY (ano, turma_id)
    REFERENCES gradebook.conselho_sessao(ano, turma_id)
);

ALTER TABLE gradebook.conselho_sessao
  ADD CONSTRAINT conselho_sessao_fechamento_fk FOREIGN KEY (fechamento_atual_id)
  REFERENCES gradebook.conselho_fechamento(id);

CREATE TABLE gradebook.conselho_fechamento_item (
  fechamento_id BIGINT NOT NULL,
  aluno_id INTEGER NOT NULL,
  elegivel BOOLEAN NOT NULL,
  motivo_elegibilidade TEXT NOT NULL,
  decisao SMALLINT NULL,
  favoraveis INTEGER NULL,
  contrarios INTEGER NULL,
  CONSTRAINT conselho_fechamento_item_pk PRIMARY KEY (fechamento_id, aluno_id),
  CONSTRAINT conselho_fechamento_item_decisao_ck CHECK (decisao IS NULL OR decisao IN (1, 2, 3)),
  CONSTRAINT conselho_fechamento_item_votos_ck CHECK (
    (favoraveis IS NULL AND contrarios IS NULL) OR (favoraveis >= 0 AND contrarios >= 0)
  ),
  CONSTRAINT conselho_fechamento_item_motivo_ck CHECK (btrim(motivo_elegibilidade) <> ''),
  CONSTRAINT conselho_fechamento_item_fechamento_fk FOREIGN KEY (fechamento_id)
    REFERENCES gradebook.conselho_fechamento(id),
  CONSTRAINT conselho_fechamento_item_aluno_fk FOREIGN KEY (aluno_id)
    REFERENCES gradebook.aluno(id)
);

CREATE INDEX conselho_sessao_hist_turma_idx
  ON gradebook.conselho_sessao_historico (ano, turma_id, alterado_em DESC, id DESC);
CREATE INDEX conselho_votacao_hist_turma_idx
  ON gradebook.conselho_votacao_historico (ano, turma_id, alterado_em DESC, id DESC);
CREATE INDEX conselho_decisao_cmd_turma_idx
  ON gradebook.conselho_decisao_comando (ano, turma_id, alterado_em DESC, id DESC);
CREATE INDEX conselho_fechamento_turma_idx
  ON gradebook.conselho_fechamento (ano, turma_id, sequencia DESC);

REVOKE ALL ON gradebook.conselho_sessao, gradebook.conselho_sessao_historico,
  gradebook.conselho_idempotencia, gradebook.conselho_votacao, gradebook.conselho_votacao_historico,
  gradebook.conselho_decisao_comando, gradebook.conselho_fechamento,
  gradebook.conselho_fechamento_item FROM PUBLIC;
REVOKE ALL ON SEQUENCE gradebook.conselho_sessao_historico_id_seq,
  gradebook.conselho_votacao_historico_id_seq,
  gradebook.conselho_decisao_comando_id_seq,
  gradebook.conselho_fechamento_id_seq FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE ON gradebook.conselho_sessao TO gradebook_app;
GRANT SELECT, INSERT ON gradebook.conselho_sessao_historico TO gradebook_app;
GRANT SELECT, INSERT ON gradebook.conselho_idempotencia TO gradebook_app;
GRANT SELECT, INSERT, UPDATE ON gradebook.conselho_votacao TO gradebook_app;
GRANT SELECT, INSERT ON gradebook.conselho_votacao_historico TO gradebook_app;
GRANT SELECT, INSERT ON gradebook.conselho_decisao_comando TO gradebook_app;
GRANT SELECT, INSERT ON gradebook.conselho_fechamento TO gradebook_app;
GRANT SELECT, INSERT ON gradebook.conselho_fechamento_item TO gradebook_app;
GRANT USAGE, SELECT ON SEQUENCE gradebook.conselho_sessao_historico_id_seq TO gradebook_app;
GRANT USAGE, SELECT ON SEQUENCE gradebook.conselho_votacao_historico_id_seq TO gradebook_app;
GRANT USAGE, SELECT ON SEQUENCE gradebook.conselho_decisao_comando_id_seq TO gradebook_app;
GRANT USAGE, SELECT ON SEQUENCE gradebook.conselho_fechamento_id_seq TO gradebook_app;

COMMIT;
