-- #674 — trilha humana mínima e append-only para diagnósticos de importação.
-- Não altera o snapshot de achados atuais nem qualquer fato acadêmico.
BEGIN;

CREATE TABLE gradebook.importacao_diagnostico_tratamento (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnostico_origem_id  BIGINT NOT NULL,
  ano                    SMALLINT NOT NULL,
  arquivo                TEXT NOT NULL,
  hash                   BYTEA NOT NULL,
  chave                  TEXT NOT NULL,
  nivel                  TEXT NOT NULL,
  codigo                 TEXT NOT NULL,
  turma_codigo           TEXT NULL,
  disciplina             TEXT NULL,
  periodo                TEXT NULL,
  aluno_numero           SMALLINT NULL,
  campo                  TEXT NOT NULL,
  rotulo                 TEXT NULL,
  acao                   SMALLINT NOT NULL,
  nota                   TEXT NULL,
  chave_idempotencia     TEXT NOT NULL,
  registrado_por         UUID NOT NULL,
  registrado_em          TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),

  CONSTRAINT importacao_diagnostico_tratamento_ano_fk FOREIGN KEY (ano)
    REFERENCES gradebook.ano_letivo(ano),
  CONSTRAINT importacao_diagnostico_tratamento_ano_ck CHECK (ano = 2026),
  CONSTRAINT importacao_diagnostico_tratamento_origem_ck CHECK (diagnostico_origem_id > 0),
  CONSTRAINT importacao_diagnostico_tratamento_arquivo_ck CHECK (
    char_length(btrim(arquivo)) BETWEEN 1 AND 255
  ),
  CONSTRAINT importacao_diagnostico_tratamento_hash_ck CHECK (octet_length(hash) = 32),
  CONSTRAINT importacao_diagnostico_tratamento_chave_ck CHECK (
    char_length(btrim(chave)) BETWEEN 1 AND 320
  ),
  CONSTRAINT importacao_diagnostico_tratamento_nivel_ck CHECK (
    nivel IN ('warning', 'blocking-error')
  ),
  CONSTRAINT importacao_diagnostico_tratamento_codigo_ck CHECK (
    codigo IN (
      'invalid-text', 'negative-grade', 'invalid-precision', 'invalid-maximum',
      'duplicate-student-number', 'source-unavailable', 'above-maximum'
    )
  ),
  CONSTRAINT importacao_diagnostico_tratamento_aluno_ck CHECK (
    aluno_numero IS NULL OR aluno_numero > 0
  ),
  CONSTRAINT importacao_diagnostico_tratamento_campo_ck CHECK (
    campo IN ('assessment', 'term-result', 'recovery', 'configuration', 'student', 'file')
  ),
  CONSTRAINT importacao_diagnostico_tratamento_acao_ck CHECK (acao IN (1, 2)),
  CONSTRAINT importacao_diagnostico_tratamento_nota_ck CHECK (
    (acao = 1 AND nota IS NULL)
    OR (acao = 2 AND nota IS NOT NULL AND char_length(btrim(nota)) BETWEEN 3 AND 2000)
  ),
  CONSTRAINT importacao_diagnostico_tratamento_idempotencia_ck CHECK (
    char_length(chave_idempotencia) BETWEEN 8 AND 120
    AND chave_idempotencia ~ '^[A-Za-z0-9._:-]+$'
  ),
  CONSTRAINT importacao_diagnostico_tratamento_idempotencia_uk UNIQUE (chave_idempotencia)
);

CREATE INDEX importacao_diagnostico_tratamento_ano_em_idx
  ON gradebook.importacao_diagnostico_tratamento (ano, registrado_em DESC, id DESC);

CREATE INDEX importacao_diagnostico_tratamento_identidade_idx
  ON gradebook.importacao_diagnostico_tratamento
    (ano, arquivo, chave, registrado_em DESC, id DESC);

REVOKE ALL ON TABLE gradebook.importacao_diagnostico_tratamento FROM PUBLIC;
REVOKE ALL ON TABLE gradebook.importacao_diagnostico_tratamento FROM gradebook_app;
REVOKE ALL ON SEQUENCE gradebook.importacao_diagnostico_tratamento_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE gradebook.importacao_diagnostico_tratamento_id_seq FROM gradebook_app;

GRANT SELECT, INSERT ON TABLE gradebook.importacao_diagnostico_tratamento TO gradebook_app;
GRANT USAGE, SELECT ON SEQUENCE gradebook.importacao_diagnostico_tratamento_id_seq TO gradebook_app;

COMMIT;
