/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.banco-notas.runtime-homologation.template.jsonc --include-runtime=false --env-interface=BancoNotasRuntimeHomologationEnv worker-configuration.runtime-homologation.d.ts` (hash: 446973369a37babf2441609dd4d9014f)
interface __BaseEnv_BancoNotasRuntimeHomologationEnv {
  BANCO_NOTAS_DB: D1Database;
  ASSETS: Fetcher;
  RUNTIME_ENVIRONMENT: 'homologation';
  TENANT_ID: 'f04e0fa3-b8dc-4f77-be3c-7dfda0635188';
  BANCO_NOTAS_ADDIN_AUDIENCE: '73ab83d3-00ba-494a-a1f8-586d250d420a';
  BANCO_NOTAS_ADDIN_SCOPE: 'BancoNotas.Sync';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./infra/banco-notas/cloudflare/runtime-homologation-worker');
  }
  interface Env extends __BaseEnv_BancoNotasRuntimeHomologationEnv {}
}
interface BancoNotasRuntimeHomologationEnv extends __BaseEnv_BancoNotasRuntimeHomologationEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      'RUNTIME_ENVIRONMENT' | 'TENANT_ID' | 'BANCO_NOTAS_ADDIN_AUDIENCE' | 'BANCO_NOTAS_ADDIN_SCOPE'
    >
  > {}
}
