/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.student-portal.jsonc --include-runtime=false --strict-vars=false --env-interface=PortalWorkerEnv workers/student-portal/env.d.ts` (hash: 3106920adc5b6423b3ded1496b464c9d)
interface __BaseEnv_PortalWorkerEnv {
	PORTAL_ENVIRONMENT: string;
	PORTAL_ORIGIN: string;
	PORTAL_ADMIN_TENANT_ID: string;
	PORTAL_DB?: Hyperdrive;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface PreviewEnv {
		PORTAL_ENVIRONMENT: string;
		PORTAL_ORIGIN: string;
		PORTAL_ADMIN_TENANT_ID: string;
	}
	interface ProductionEnv {
		PORTAL_DB: Hyperdrive;
		PORTAL_ENVIRONMENT: string;
		PORTAL_ORIGIN: string;
		PORTAL_ADMIN_TENANT_ID: string;
	}
	interface Env extends __BaseEnv_PortalWorkerEnv {}
}
interface PortalWorkerEnv extends __BaseEnv_PortalWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PORTAL_ENVIRONMENT" | "PORTAL_ORIGIN" | "PORTAL_ADMIN_TENANT_ID">> {}
}
